In [28]:
import matplotlib.pyplot as plt
import numpy as np
import os
from PIL import Image
#import plotly.graph_objs as go
# 创建初始帧
#fig = go.Figure()

# 遍历所有bmp图片，创建动画帧
frames = []
# 打开文本文件并读取所有行
folder_path = './data/'
for filename in sorted(os.listdir(folder_path)):
    
    if not filename.endswith('.txt'):
        continue

    with open(os.path.join(folder_path, filename), 'r') as file:
        lines = file.readlines()
#     print(lines)
    # 创建一个空数组来存储转换后的数据
    data = []
    print(filename)
    # 遍历每一行并将其分割成一系列的值
    for line in lines:
        values = line.split()
        data.append(values)

    data_float = []
    for row in data:
        # 将每一行中的字符串转换为浮点数
        row_float = [float(val) for val in row]
        # 删除第一列和第五列
        row_float.pop(0)
        row_float.pop(-1)
        # 将小于0.5的行删除
        if row_float[2] >= 0.1 and row_float[1] >= 0:
            data_float.append(row_float)

    # 将包含浮点数的列表转换为NumPy数组
    data_array = np.array(data_float)
    print(data_array)


t=16_x=0.1_r=0.001_zdrop=0.001+0.061_zk+0.06_pure_data.txt
[[8.0000004e-03 8.9999998e-04 9.5918369e-01]
 [2.2666667e-02 8.9999998e-04 9.5918369e-01]
 [3.3666667e-02 8.9999998e-04 9.5918369e-01]
 ...
 [1.2633334e-01 4.0100001e-02 4.4897914e-01]
 [1.3733333e-01 4.0100001e-02 4.4897914e-01]
 [1.5200000e-01 4.0100001e-02 2.2448952e-01]]
t=18_x=0.1_r=0.001_zdrop=0.001+0.061_zk+0.06_pure_data.txt
[[8.0000004e-03 8.9999998e-04 9.5918369e-01]
 [2.2666667e-02 8.9999998e-04 9.5918369e-01]
 [3.3666667e-02 8.9999998e-04 9.5918369e-01]
 ...
 [1.2633334e-01 4.0100001e-02 4.4897914e-01]
 [1.3733333e-01 4.0100001e-02 4.4897914e-01]
 [1.5200000e-01 4.0100001e-02 2.2448952e-01]]
t=20_x=0.1_r=0.001_zdrop=0.001+0.061_zk+0.06_pure_data.txt
[[8.0000004e-03 8.9999998e-04 9.5918369e-01]
 [2.2666667e-02 8.9999998e-04 9.5918369e-01]
 [3.3666667e-02 8.9999998e-04 9.5918369e-01]
 ...
 [1.2633334e-01 4.0100001e-02 4.4897914e-01]
 [1.3733333e-01 4.0100001e-02 4.4897914e-01]
 [1.5200000e-01 4.0100001e-02 2.2448952e-

IndexError: pop from empty list

In [22]:
filename


'x=0.1_r=0.001_zdrop=0.001+0.061_zk+0.06_pure_data.txt'

In [23]:
os.path.join(folder_path, filename)

'./data/x=0.1_r=0.001_zdrop=0.001+0.061_zk+0.06_pure_data.txt'

In [24]:
os.path.join(filename)

'x=0.1_r=0.001_zdrop=0.001+0.061_zk+0.06_pure_data.txt'

In [12]:
    data = []
#     print(i)
#     i=i+1
    # 遍历每一行并将其分割成一系列的值
    for line in lines:
            # 跳过空行
        if not line.strip():
            continue
        values = line.split()
        data.append(values)

    data_float = []
    for row in data:
        # 将每一行中的字符串转换为浮点数
        if not values[0].isdigit():
            continue
        row_float = [float(val) for val in row]
        if len(row_float) < 3:
            continue
        # 删除第一列和第五列
        row_float.pop(0)
        row_float.pop(-1)
        # 将小于0.5的行删除
        if row_float[2] >= 0.1 and row_float[1] >= 0:
            data_float.append(row_float)

    # 将包含浮点数的列表转换为NumPy数组
    data_array = np.array(data_float)


In [13]:
    data_array

array([], dtype=float64)

In [26]:
import matplotlib.pyplot as plt
import numpy as np
# 打开文本文件并读取所有行
with open('t=32_x=0.1_r=0.001_zdrop=0.001+0.061_zk+0.06_pure_data.txt', 'r') as file:
    lines = file.readlines()

# 创建一个空数组来存储转换后的数据
data = []

# 遍历每一行并将其分割成一系列的值
for line in lines:
    values = line.split()
    data.append(values)

data_float = []
for row in data:
    # 将每一行中的字符串转换为浮点数
    row_float = [float(val) for val in row]
    # 删除第一列和第五列
    row_float.pop(0)
    row_float.pop(-1)
    # 将小于0.5的行删除
    if row_float[2] >= 0.1 and row_float[1] >= 0:
        data_float.append(row_float)

# 将包含浮点数的列表转换为NumPy数组
data_array = np.array(data_float)
print(data_array)


[[8.0000004e-03 8.9999998e-04 9.5918369e-01]
 [2.2666667e-02 8.9999998e-04 9.5918369e-01]
 [3.3666667e-02 8.9999998e-04 9.5918369e-01]
 ...
 [1.2633334e-01 4.0100001e-02 4.4897914e-01]
 [1.3733333e-01 4.0100001e-02 4.4897914e-01]
 [1.5200000e-01 4.0100001e-02 2.2448952e-01]]
